kind: Service
apiVersion: v1
metadata:
  name: nodeapp
spec:
  selector:
    app: nodeapp
  ports:
  - targetPort: 80
    port: 80
    nodePort: 31444
  type: NodePort  


---
apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: sbabburu/nodeapp:tagVersion
      ports:
        - containerPort: 80
